mangd/todos/routes.py
# flask imports
from flask import flash, redirect, render_template, request, session, url_for, Blueprint

# datetime for todos
from datetime import datetime

# import local modules:
from mangd.extras import login_required
from mangd.googlecalendar import service
from mangd import db
from mangd.database import todo

todos_app = Blueprint('todos', __name__)

# homepage/ todos route
@todos_app.route("/", methods=("GET", "POST"))
@login_required
def todos():
    if request.method == "POST":
        title = request.form["todo-item"]
        deadline = None
        google_id = None
        # order = request.form['todo-filter']
        # check that the user provided a todo title before adding it
        if not title:
            flash("Please provide a text describtion for your todo", "danger")
            return redirect(url_for("todos.todos"))

        # if the user provided a deadline, reformat deadline from html to a python datetime object
        if request.form["deadline"]:
            deadline = datetime.strptime(request.form["deadline"], "%Y-%m-%dT%H:%M")
            created_event = (
                service.events()
                .quickAdd(calendarId="primary", text=f"{title} at {deadline}")
                .execute()
            )
            # save google id for the event so that the user can update/delete event later
            google_id = created_event["id"]

        # assign a stat value of false to every todo to mark it as pending
        stat = False

        # save new todo to database and commit changes
        td = todo(title, stat, deadline, session["user_id"], google_id)
        db.session.add(td)
        db.session.commit()
        return redirect(url_for("todos.todos"))

    page = request.args.get("page", 1, type=int)
    my_todos = (
        todo.query.filter_by(user=session["user_id"])
        .order_by(todo.stat, todo.deadline)
        .paginate(page=page, per_page=10)
    )
    return render_template("todos.html", my_todos=my_todos, filter="all")


@todos_app.route("/filter_by/<_filter>")
def todo_filter(_filter):

    page = request.args.get("page", 1, type=int)
    if _filter == "completed":
        my_todos = (
            todo.query.filter_by(user=session["user_id"], stat=True)
            .order_by(todo.deadline)
            .paginate(page=page, per_page=10)
        )
    elif _filter == "pending":
        my_todos = (
            todo.query.filter_by(user=session["user_id"], stat=False)
            .order_by(todo.deadline)
            .paginate(page=page, per_page=10)
        )
    elif _filter == "has-due-date":
        my_todos = (
            todo.query.filter((todo.user==session["user_id"]) & (todo.deadline != None))
            .order_by(todo.deadline)
            .paginate(page=page, per_page=10)
        )
    
    return render_template("todos.html", my_todos=my_todos, filter=_filter)

# status update route
@todos_app.route("/status/<int:todo_id>")
@login_required
def stat(todo_id):
    # query for todo using the todo id
    td = todo.query.filter_by(id=todo_id).first()

    # if status is pending('false') change it to completed("True")
    if td.stat == True:
        td.stat = False
    else:
        td.stat = True

    # commit changes to the database
    db.session.commit()
    return redirect(url_for("todos.todos"))


# delete route for todos
@todos_app.route("/delete/<int:todo_id>")
@login_required
def delete(todo_id):

    # query for todo using todo id
    td = todo.query.filter_by(id=todo_id).first()

    # if todo was added to user calendar, delete from there as well
    if td.google_id:
        service.events().delete(calendarId="primary", eventId=td.google_id).execute()
    db.session.delete(td)
    db.session.commit()
    return redirect(url_for("todos.todos"))

mangd/users/routes.py
import os
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash


# import local modules:
from mangd import db, oauth, mail
from mangd.database import user
from mangd.extras import login_required

# imports for flask-mail
from flask_mail import Message
users = Blueprint('users', __name__)

# register function
@users.route("/register", methods=("GET", "POST"))
def register():
    if request.method == "POST":
        error = None
        _username = request.form["username"]
        email = request.form["email"]
        password = request.form["password"]

        # check if the user provided a username, assign an error messsage
        if not _username:
            error = "Username is required."

        # Check if user provided email:
        elif not email:
            error = "Must provide an email"

        # if username already exists, return error message
        elif user.query.filter_by(username=_username).first():
            error = "Username already exists"

        # Check if the email has already been regustered for another user:
        elif user.query.filter_by(email=email).first():
            error = "Email is already in use."

        # if the lenght of username is less than 6 characcters, return error message
        elif len(_username) < 6:
            error = "Username must be at least 6 characters long"

        # check if user provided a password.
        elif not password:
            error = "Password is required."

        # check if the password provided matches with the confirmation input
        elif password != request.form["confirmation"]:
            error = "Passwords don't match."

        # check if the lenth of password if at least 6 characters long
        elif len(password) < 6:
            error = "Password must be at least 6 characters long"

        # if there are no errors, add user to database and commit
        if error is None:
            usr = user(_username, generate_password_hash(password), email)
            db.session.add(usr)
            db.session.commit()

            # let the user know they've been succesfully registered and redirect them to the login page
            flash("You Have Been Registered Successfully!", "success")
            return redirect(url_for("users.login"))

        # if there was an error during registration, flask error message
        flash(error, "danger")
    return render_template("register.html")


# login fucntion
@users.route("/login", methods=("GET", "POST"))
def login():
    if request.method == "POST":

        error = None
        _username = request.form["username"]
        password = request.form["password"]

        # Ensure username was submitted
        if not _username:
            error = "must provide username"

        # Ensure password was submitted
        elif not password:
            error = "must provide password"

        # Query database for username
        usr = user.query.filter_by(username=_username).first()

        if not usr:
            usr = user.query.filter_by(email=_username).first()

        # check if user exists
        if not usr:
            error = "invalid user or email."

        # Ensure username exists and password is correct
        elif not check_password_hash(usr.password, password):
            error = "invalid password"

        # if there are no errors, clear any previous sessions,
        # and initiate a new session for user
        if error is None:
            session.clear()
            session["user_id"] = usr._id
            return redirect(url_for("todos.todos"))

        # let the user name what went wrong using the flash function
        flash(error, "danger")

    # User reached route via GET (as by clicking a link or via redirect)
    return render_template("login.html")



@users.route("/forgot_password", methods=("GET", "POST"))
def forgot_password():
    if request.method == "POST":
        email = request.form["email"]
        if not user.query.filter_by(email=email).first():
            flash(" There is not an account registered under that email.", "danger")
        else:
            _user = user.query.filter_by(email=email).first()
            _token = _user.get_reset_token()

            # send email using gmail:
            msg = Message(
                "Password Reset", sender="criscodesnyc@gmail.com", recipients=[email]
            )
            msg.body = f"""To reset your password, please visit: 
            {url_for('users.reset_password', token=_token, _external=True)}"""
            mail.send(msg)
            flash(
                "An email has been sent to you account with the link to reset your password",
                "success",
            )
            return redirect(url_for("users.login"))
    return render_template("forgotpassword.html")


@users.route("/reset_password/<token>", methods=("GET", "POST"))
def reset_password(token):
    if request.method == "POST":
        _user = user.verify_reset_token(token)
        if not _user:
            flash("That is an invalid or expired token", "danger")
            return redirect(url_for("forgot_password"))
        else:
            error = None
            _password = request.form["password"]

            # check if user provided a password
            if not _password:
                error = "Password is required."

            # check if the password provided matches with the confirmation input
            elif _password != request.form["confirmation"]:
                error = "Passwords don't match."

            # check if the lenth of password if at least 6 characters long
            elif len(_password) < 6:
                error = "Password must be at least 6 characters long."
            # if no errors ocured, commit new password for the user to the database, provide success mesage to user
            elif error is None:
                _user.password = generate_password_hash(_password)
                db.session.commit()
                flash("Your password has been reset successfully", "success")
                return redirect("users.login")
        flash(error, "danger")
    return render_template("resetpassword.html")

# user logout
@users.route("/logout")
@login_required
def logout():
    session.clear()
    return redirect(url_for("users.login"))

mangd/templates/forgotpassword.html
{% extends "layout.html" %} {% block title %} Reset Password {% endblock %}
{%block main %}
<div class="container">
  <div id="login-row" class="row justify-content-center align-items-center">
    <div id="login-column" class="col-md-6">
      <div id="login-box" class="col-md-12">
        <form action="/forgot_password" method="Post">
          <div class="form-group">
            <input autocomplete="off"
              autofocus
              class="form-control"
              name="email"
              id="email"
              placeholder="Email"
              type="text"
            />
          </div>
          <button class="btn btn-primary" type="submit">Send Email</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mangd/templates/layout.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" 
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
                crossorigin="anonymous">
        </script>
        
        <title>MANGD{% block title %}{% endblock %}</title>
    </head>
    <body style="background-color: #F9F6EE">
        <header class="site-header">
        <!--navegation bar-->
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <div class="container">
                <a href="/" class="navbar-brand">MANGD</a>
                <button
                  class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarToggle"
                  aria-controls="navbarToggle"
                  aria-expanded="false"
                  aria-label="Toggle navigation"
                 >
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarToggle">
                    {% if session.user_id %}
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href={{url_for('users.logout')}}>Log Out</a>
                    </div>
                    {% else %}
                    <div class="navbar-nav ml-auto">
                        <a class="nav-item nav-link" href={{url_for('users.register')}}>Register</a>
                        <a class="nav-item nav-link" href={{url_for('users.login')}}>Log In</a>
                    </div>
                {% endif %}
                </div>
            </div>
        </nav>
    </header>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <header>
                    <div class="alert alert-primary border text-center" role="alert">
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </div>
                </header>
                {% endif %}
            {% endwith %}
        <main class="container p-5 align-middle text-center">
            <div class="container py-5 h-100">
                <div class="container">
                    <div id="flash-row" class="row justify-content-center align-items-center">
                         <div id="flash-column" class="col-md-6">
                             <div id="flash-box" class="col-md-12">
                                {% with messages = get_flashed_messages(with_categories=true) %}
                                    {% if messages %}
                                        {% for category, message in messages %}
                                            <div class="alert alert-{{ category }}" role="alert">
                                                 {{ message }}
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                                {% endwith %}
                            </div>
                        </div>
                    </div>
                {% block main %}{% endblock %}
            </div>
        </main>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
    </html>

mangd/templates/login.html
{% extends "layout.html" %} {% block title %} Log In {% endblock %} {% block
main %}
<div class="container">
  <div id="login-row" class="row justify-content-center align-items-center">
    <div id="login-column" class="col-md-6">
      <div id="login-box" class="col-md-12">
        <form action="/login" method="POST">
          <div class="form-group">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="username"
              placeholder="Username or Email"
              type="text"
            />
          </div>
          <div class="form-group">
            <input
              class="form-control"
              name="password"
              placeholder="Password"
              type="password"
            />
          </div>
          <button class="btn btn-primary" type="submit">Log In</button>
        </form>
        <div class="pt-3">
              <a class="btn btn-outline-dark" href="{{ url_for('users.google_login')}}" role="button" style="text-transform:none">
                <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
                Login with Google
              </a>
          </div>
          <div class="pt-3">
            <small class="text-muted">
              Don't Have An Account?
              <a class="ml-2" href="{{ url_for('users.register')}}"> Register!</a>
            </small>
          </div>
          <div class="pt-3">
            <small class="text-muted">
              <a class="mr-2" href="{{ url_for('users.forgot_password')}}">Forgot Passwor?</a>
            </small>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  </div>
  {% endblock %}

mangd/templates/register.html
{% extends "layout.html" %} {% block title %} Register {% endblock %} {% block
main %}
<div class="container">
  <div id="login-row" class="row justify-content-center align-items-center">
    <div id="login-column" class="col-md-6">
      <div id="login-box" class="col-md-12">
        <form action="/register" method="POST">
          <div class="form-group">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="username"
              placeholder="Username"
              type="text"
            />
          </div>
          <div class="form-group">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="email"
              placeholder="Email"
              type="text"
            />
          </div>
          <div class="form-group">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="password"
              placeholder="Password"
              type="password"
            />
          </div>
          <div class="form-group">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="confirmation"
              placeholder="Re-enter Password"
              type="password"
            />
          </div>
          <button class="btn btn-primary" type="submit">Register</button>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="pt-3">
  <a class="btn btn-outline-dark" href="{{ url_for('users.google_login')}}" role="button" style="text-transform:none">
    <img width="20px" style="margin-bottom:3px; margin-right:5px" alt="Google sign-in" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
    Login with Google
  </a>
</div>
<div class="pt-3">
  <small class="text-muted">
    Already Have An Account?
    <a class="ml-2" href="{{ url_for('users.login')}}"> Sign In!</a>
  </small>
</div>
{% endblock %}

mangd/templates/resetpassword.html
{% extends "layout.html" %} {% block title %} Enter New Password {% endblock %}
{% block main %}
<div class="container">
  <div id="login-row" class="row justify-content-center align-items-center">
    <div id="login-column" class="col-md-6">
      <div id="login-box" class="col-md-12">
        <form action="/reset_password/<token>" method="post">
          <div class="form-group">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="password"
              placeholder="Enter New Password"
              type="password"
            />
          </div>
          <div class="form-group" method="post">
            <input
              autocomplete="off"
              autofocus
              class="form-control"
              name="confirmation"
              placeholder="Re-enter New Password"
              type="password"
            />
          </div>
          <button class="btn btn-primary" type="submit">Change Password</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mangd/templates/todos.html
{% extends "layout.html" %} {% block title %} index {% endblock %} {% block main
%}
<script>
  function parse_time(date_time) {
    let m = moment(date_time, "YYYY-MM-DD hh:mm:ss");
    return m.format("dddd, MMM Do YYYY, [by] h:mm a");
  }
</script>
<!--container py-5 ensures that the content stays centered-->
<div class="container py-5 h-100" >
  <h2><p>My Todos </p></h2>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#todoModal">
    <i class="fa fa-plus"></i> Add a Todo
  </button> 

<!-- View options section -->

  <div class="row m-1 p-3 px-5 justify-content-end">
    <div class="col-auto d-flex align-items-center">
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter by
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="/filter_by/completed" data-value="completed">Completed</a>
          <a class="dropdown-item" href="/filter_by/pending" data-value="pending">Pending</a>
          <a class="dropdown-item" href="/filter_by/has-due-date" data-value="has-due-date">Has due date</a>
          <a class="dropdown-item" href="/" data-value="all">All </a>
        </div>
      </div>
    </div>
  </div>
  

    <!--list of todos for the user-->
    {%for todo in my_todos.items %}
    <ul class="list-group list-group-horizontal-lg rounded-0 bg-transparent">
      <!--todo title-->
      <li class="list-group-item p-2 rounded-0 border-0 bg-transparent">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&display=swap" rel="stylesheet">
        <label class="form-check-label" for="{{todo.id}}">
        {% if todo.stat==True%}
          <h3 class="text-muted"><del>{{todo.title}}</del></h3>
        {% else %}
          <h3><b>{{todo.title}}</b></h3>
        {% endif %}
        </label>
      </li>
      <li class="list-group-item ml-auto rounded-0 border-0 bg-transparent">
        <ul class="list-group list-group-horizontal-lg rounded-0 bg-transparent">
          <li class="list-group-item ml-auto rounded-0 border-0 bg-transparent">
            {% if todo.deadline != None%}
              <div
                class="
                  py-2
                  px-3
                  me-2
                  border border-warning
                  rounded-3
                  d-flex
                  align-items-center
                  bg-light
                "
              >
                <p class="small mb-0">
                due on:
                <script type="text/javascript">
                  document.write(parse_time("{{ todo.deadline }}"));
                </script>
                </p>
              </div>
            {% endif %}
          </li>
        <li class="list-group-item ml-auto rounded-0 border-0 bg-transparent">
          <a href="/status/{{todo.id}}">
            {% if todo.stat == True %}
            <button type="button" class="btn btn-success ml-auto">COMPLETED</button>
            {% else %}
            <button
              href="/status/{{todo.id}}"
              type="button"
              class="btn btn-warning ml-auto"
            >
              Pending...
            </button>
            {% endif %}
          </a>
          <a href="/delete/{{todo.id}}">
            <button class="btn btn-danger ml-auto">Delete</button>
          </a>
            </li>
          </ul>
        </li>
    
    
      </li>
    </ul>
      {% endfor %}
    


<!--pagination-->
<div class="mr-auto">
  {% for page_num in my_todos.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)%}
    {% if page_num %}
      {% if my_todos.page == page_num%}
        <a class="btn btn-info mb-4" href="{{ url_for('todos.todos', page=page_num) }}">{{page_num}}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('todos.todos', page=page_num) }}">{{page_num}}</a>
      {% endif %}
    {% endif %}
  {% endfor %}
</div>
  
<div class="modal fade" id="todoModal" tabindex="-1" role="dialog" aria-labelledby="todoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="todoModalLabel">Add a To-Do</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="/" method="POST">
            <input
              autocomplete="off"
              placeholder="Enter To-Do Item..."
              type="text"
              name="todo-item"
              class="form-control form-control-lg"
            />
            <label for"deadline" class="text-muted">Add a deadline:</label>
            <input type="datetime-local" id="deadline" name="deadline" placeholder="deadline" />
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}